name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch:
          - x64
          - arm64
        node-version:
          - node18
        os:
          - linux
          - macos
          - win

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package Node.js binary with pkg
        id: pkg-action
        uses: lando/pkg-action@v2
        with:
          entrypoint: ./bin/run
          arch: ${{ matrix.arch }}
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}

  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download binaries
        id: download
        uses: actions/download-artifact@3
        with:
          path: binaries


      - name: deubg ls binaries
        shell: bash
        run: |
          ls -la binaries

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            ${{steps.download.outputs.download-path}}
          name: Release ${{ github.ref }}/*
          tag_name: ${{ github.ref }}
