name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch:
          - x64
          - arm64
        node-version:
          - node16
        os:
          - linux
          - macos
          - win

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package Node.js binary with pkg
        id: pkg-action
        uses: lando/pkg-action@v2
        with:
          entrypoint: ./bin/run
          arch: ${{ matrix.arch }}
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.pkg-action.outputs.file }}
          name: Release-${{ matrix.os }}-${{ matrix.arch }}
          tag_name: ${{ github.ref }}

